import org.gradle.internal.impldep.org.eclipse.jgit.lib.ObjectChecker.type

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    groovy
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.codehaus.groovy:groovy-all:2.4.7")
//    implementation("org.apache.groovy:groovy:2.4.7")
    implementation("org.apache.commons:commons-csv:1.4")
    api("org.apache.commons:commons-lang3:3.5")
    api("org.apache.logging.log4j:log4j-core:2.6.1")
    api("com.github.javafaker:javafaker:0.13")
    api("org.janusgraph:janusgraph-all:1.0.0-rc1")
    implementation("org.apache.tinkerpop:gremlin-driver:3.2.9")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.0.1")
}

sourceSets {
    main {
        java {
            exclude("src/main/java/com/ibm/janusgraph/utils")
        }
        groovy {
            srcDir("src/main/groovy/com/ibm/janusgraph/utils") }
    }
}

tasks.register<Copy>("copyRuntimeJars") {
    from(configurations.runtimeClasspath)
    into(file("$buildDir/libs"))
}

tasks {
    val fatJar = register<Jar>("fatJar") {
        dependsOn.addAll(listOf("compileJava", "compileGroovy", "processResources"))
        dependsOn(configurations.runtimeClasspath)
        archiveClassifier.set("standalone")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        manifest {
            attributes["Main-Class"] = "com.example.MyApp"
            attributes["Zip-File"] = "true"
            attributes["Zip64"] = "true"
        }
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA", "META-INF/*.MF")
        val sourcesMain = sourceSets.main.get()
        val content = configurations.runtimeClasspath.get()
                .map { if (it.isDirectory) it else zipTree(it)}
                .plus(sourcesMain.output)
        from(content)
    }
}

group = "janusgraph-utils"
version = "0.0.1-SNAPSHOT"
description = "janusgraph-utils"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
